wandb_version: 1

model_type:
  desc: null
  value: reinformer
dataset_dir:
  desc: null
  value: assets
context_len:
  desc: null
  value: 100
n_blocks:
  desc: null
  value: 4
embed_dim:
  desc: null
  value: 256
n_heads:
  desc: null
  value: 8
dropout_p:
  desc: null
  value: 0.1
grad_norm:
  desc: null
  value: 0.25
tau:
  desc: null
  value: 0.99
batch_size:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.0001
wd:
  desc: null
  value: 0.0001
warmup_steps:
  desc: null
  value: 5000
max_train_iters:
  desc: null
  value: 10
num_updates_per_iter:
  desc: null
  value: 5000
device:
  desc: null
  value: cuda:1
seed:
  desc: null
  value: 2024
init_temperature:
  desc: null
  value: 0.1
use_wandb:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718592119
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.17.1
      8:
      - 3
      - 5
      13: windows-amd64
