# traditional edge finder 
EDGES_LOWER_BOUND: int = 100
EDGES_UPPER_BOUND: int = 200
HOUGH_ANGLE_UPPER_BOUND: int = 160
HOUGH_ANGLE_LOWER_BOUND: int = 100
HOUGH_CONFIDENT_THRESHOLD: int = 85
THRESH_UPPER_BOUND: int = 255
THRESH_LOWER_BOUND: int = 100
