# traditional edge finder 
EDGES_LOWER_BOUND: int = 120
EDGES_UPPER_BOUND: int = 240
HOUGH_ANGLE_UPPER_BOUND: int = 160
HOUGH_ANGLE_LOWER_BOUND: int = 100
HOUGH_CONFIDENT_THRESHOLD: int = 55
THRESH_UPPER_BOUND: int = 255
THRESH_LOWER_BOUND: int = 100
